### Numpy 기본 연산
#### 1) 넘파이의 기본 연산은 ndarray 라는 객체로 만들어서 수행 : np.array() 함수 사용

In [1]:
import numpy as np

In [ ]:
# 한글과 영어 입력

In [ ]:
list1 = [1, 2, 3]                   # 리스트 생성
list2 = [4, 5.0, 6]                 # 리스트 원소 중 한개라도 실수(float)이며, 리스트 자료형은 실수형

a = np.array(list1)                 # 넘파이의 array() 함수를 사용해서, 리스트를 ndarray 객체로 생성
b = np.array(list2)

c = a + b                           # np.add(list1, list2)로 연산할수도 있음
d = a - b
e = a * b
f = a / b

g = a * 2                           # ndarray 객체에 스칼라 값을 연산하면, 배열의 원소 각각에 연산
h = b + 2

In [ ]:
print('a 자료형:', type(a), type(a[0]))         # a 값은 행렬과 같으므로, a[0]는 첫번째 값
print('b 자료형:', type(b), type(b[0]))
print('c 자료형:', type(c), type(c[0]))
print('g 자료형:', type(g), type(g[0]))

a 자료형: <class 'numpy.ndarray'> <class 'numpy.int64'>
b 자료형: <class 'numpy.ndarray'> <class 'numpy.float64'>
c 자료형: <class 'numpy.ndarray'> <class 'numpy.float64'>
g 자료형: <class 'numpy.ndarray'> <class 'numpy.int64'>


In [8]:
print(c, d, e, f)
print(g, h)

[5. 7. 9.] [-3. -3. -3.] [ 4. 10. 18.] [0.25 0.4  0.5 ]
[2 4 6] [6. 7. 8.]


#### 2) 리스트 값을 사용하지 않고, 넘파이 함수로 직접 행렬 생성 

In [40]:
a = np.zeros((2,5), np.int32)               # 2행 5열의 행렬에 제로값으로 생성, 타입은 정수형
b = np.ones((3,1), np.uint8)                # 3행 1열의 행렬에 1값으로 생성, unsigned integer 형
c = np.empty((1,5), np.float64)             # 1행 5열의 행렬에 빈 값 생성, 실수형
d = np.full(6, 15, np.float32)              # 1차원 배열, 6개 값을 채우되, 원소값은 15, 실수형

In [41]:
print('c 형태:', c.shape, '   d 형태:', d.shape)

print("a 행렬값 : \n", a)
print("b 행렬값 : \n", b)

print("c 행렬값 : \n", c)
print("d 배열값 : \n", d)

c 형태: (1, 5)    d 형태: (6,)
a 행렬값 : 
 [[0 0 0 0 0]
 [0 0 0 0 0]]
b 행렬값 : 
 [[1]
 [1]
 [1]]
c 행렬값 : 
 [[ 0.62133597 -0.72008556  0.26551159  0.10854853  0.00429143]]
d 배열값 : 
 [15. 15. 15. 15. 15. 15.]


In [ ]:
print(type(a), type(a[0]), type(a[0][0]), a.dtype)      
print(type(b), type(b[0]), type(b[0][0]), b.dtype)
print(type(c), type(c[0]), c.dtype)
print(type(d), type(d[0]) , d.dtype)

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.int32'> int32
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.uint8'> uint8
<class 'numpy.ndarray'> <class 'numpy.ndarray'> float64
<class 'numpy.ndarray'> <class 'numpy.float32'> float32


#### 3) 넘파이로 난수값 행렬 생성하기

In [1]:
import numpy as np

In [3]:
np.random.seed(10)                      # random.seed() 함수 이용. seed()함수에 필요한 키값을 임의로 설정

a = np.random.rand(2, 3)                # 2행 3열 난수값 생성
b = np.random.randn(5, 1)               # 5행 1열 난수값 생성하되, 각 원소값이 정규분포를 가짐
c = np.random.rand(6)                   # 1차원 행열 난수값 생성
d = np.random.randint(1, 100, 6)        # 난수값의 범위를 1~100으로 설정, 1차원 6개 정수형 원소 생성


In [4]:
print('a 형태:', a.shape, '\n', a)          # shape은 행렬의 크기 표시
print('b 형태:', b.shape, '\n', b)
print('c 형태:', c.shape, '\n', c)
print('d 형태:', d.shape, '\n', d)

a 형태: (2, 3) 
 [[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]]
b 형태: (5, 1) 
 [[ 0.62133597]
 [-0.72008556]
 [ 0.26551159]
 [ 0.10854853]
 [ 0.00429143]]
c 형태: (6,) 
 [0.81262096 0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
d 형태: (6,) 
 [14 26 14 93 87 31]


* 행렬의 형태 변환

In [10]:
c = np.reshape(c, (2, 3))              # 형태(shape) 변경 : 1차원 행렬을 2행 3열로 변환

d = d.reshape(2,-1)                    # 형태(shape) 변경 : d 행렬을 직접 변환, 강제로 2열로 만듬

In [9]:
print('c 형태:', c.shape, '\n', c)
print('d 형태:', d.shape, '\n', d)


c 형태: (2, 3) 
 [[0.81262096 0.61252607 0.72175532]
 [0.29187607 0.91777412 0.71457578]]
d 형태: (2, 3) 
 [[14 26 14]
 [93 87 31]]


* np.arange() 함수

In [ ]:
x = np.arange(0, 10, 2)     # prmt : 시작, 종료(필수), 간격

print(x)

[0 2 4 6 8]


In [8]:
# 시작 값이 없으면 0부터 시작
# 간격(step) 값이 없으면 간격은 1

x = np.arange(20)           

print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
